config/routes.rb
Sugarcare::Application.routes.draw do
  devise_for :caregivers

  resources :caregivers do
    root to: 'caregivers#index'
    collection { post :search, to: 'caregivers#index' }
  end

end

app/models/caregiver.rb
class Caregiver < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :bio, :first_name, :job_title, :last_name, :phone_number, :years_experience, :zip_code, :city, :organization, :avatar
  attr_accessible :address

  validates :bio, presence: true
  validates :first_name, presence: true
  
  validates :job_title, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true
  validates :years_experience, presence: true
  validates :zip_code, presence: true
  validates :city, presence: true


  geocoded_by :zip_code
  after_validation :geocode 
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode  # auto-fetch address
  has_attached_file :avatar, :styles => { :square => "150x150#" }, default_url: "./app/assets/images/avatar_default/icon.png"

  validates_attachment_presence :avatar
  validates_attachment_size :avatar, :less_than => 5.megabytes
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png']
  
  RANSACKABLE_ATTRIBUTES = ["last_name"]
  RANSACKABLE_ATTRIBUTES << ["first_name"]
  RANSACKABLE_ATTRIBUTES << ["city"]
  RANSACKABLE_ATTRIBUTES << ["zip_code"]
  RANSACKABLE_ATTRIBUTES << ["job_title"]
  RANSACKABLE_ATTRIBUTES << ["email"]
  RANSACKABLE_ATTRIBUTES << ["phone_number"]
  RANSACKABLE_ATTRIBUTES << ["years_experience"]
  
  def self.ransackable_attributes auth_object = nil
      RANSACKABLE_ATTRIBUTES + _ransackers.keys
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :profile_name
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/caregivers_controller.rb
class CaregiversController < ApplicationController
  before_filter :authenticate_caregiver!, :except => [:index, :show]

  # GET /caregivers
  # GET /caregivers.json
  def index
    @search = Caregiver.search(params[:q].presence)
    # NOTE: The following line specifies the sort order.
    # This is reflected in the default sort criteria shown.
    # The user is free to remove these default criteria.
    @search.sorts = 'last_name asc' if @search.sorts.empty?
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?
    @caregivers = @search.result
    @caregivers_count = @caregivers.count
    @caregivers = @caregivers.order("last_name").page(params[:page]).per(10)
  end

  def new
    @caregiver = Caregiver.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @caregivers }
    end
  end

  # GET /caregivers/1
  # GET /caregivers/1.json
  def show
    @caregiver = Caregiver.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @caregiver }
    end
  end


  # GET /caregivers/1/edit
  def edit
    @caregiver = current_caregiver
  end

  # PUT /caregivers/1
  # PUT /caregivers/1.json
  def update
    @caregiver = current_caregiver

    respond_to do |format|
      if @caregiver.update_attributes(params[:caregiver])
        format.html { redirect_to @caregiver, notice: 'Caregiver was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @caregiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caregivers/1
  # DELETE /caregivers/1.json
  def destroy
    @caregiver = Caregiver.find(params[:id])
    @caregiver.destroy

    respond_to do |format|
      format.html { redirect_to caregivers_url }
      format.json { head :no_content }
    end
  end
end





  def create
    @caregiver = Caregiver.create(params[:caregiver])
  end

#-------------------------------------------------------------------------------

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, type)
    new_object = f.object.send "build_#{type}"
    id = "new_#{type}"
    fields = f.send("#{type}_fields", new_object, child_index: id) do |builder|
      render(type.to_s + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/caregivers_helper.rb
module CaregiversHelper
end

app/views/caregivers/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select associations: [:category] %>
  <% end %>
  <%= f.predicate_select %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</div>

app/views/caregivers/_form.html.erb
<%= simple_form_for(@caregiver) do |f| %>
  <% if @caregiver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@caregiver.errors.count, "error") %> prohibited this caregiver from being saved:</h2>

      <ul>
      <% @caregiver.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <br>
    <br>
    <%= f.input :email %>
    <%= f.input :phone_number, :input_html => {:maxlength =>14} %>
    <br>
    <br>
    <%= f.input :city %>
    <%= f.input :zip_code, :input_html => {:maxlength =>5} %>
    <%= f.input :organization %>
    <%= f.input :job_title %>
    <%= f.input :years_experience, :input_html => {:maxlength =>2,:style=> 'width: 40px'}%>

<div class="instructions"> Briefly describe your past experience and training. 
<br>
What conditions, diagnosis or disease states do you have experience with? 
<br>
What languages do you speak?
<br>
Say some interesting things about yourself. Like, what are your hobbies?
<br>
Please also note your availability here. 
<br>
<br>
<b>*500 Character Limit*</b>
</div>


<%= f.input :bio, :input_html => {:maxlength =>500, :rows => 10, :style=> 'width: 430px'}%>

<div class="avatar-upload">
  <p> Upload a new image to change photo. </p>
<%= f.file_field :avatar %>
</div>


  <div class="actions">
    <%= f.submit "Save Changes", class: "btn update-profile-btn" %>
  </div>
<% end %>

<style>

  .update-profile-btn {
  padding: 7px 20px;
  *margin-left: .5em;
  line-height: 24px;
  *line-height: 24px;
  text-decoration: none;
  text-align: center;
}
</style>

app/views/caregivers/edit.html.erb
<%= render 'form' %>

app/views/caregivers/index.html.erb
<h2>See Caregivers who work at in-home care providers near you.</h2>

<style>
select,
textarea,
input[type="text"],

.search-query .uneditable-input {
display: inline-block;
height: 40px;
padding: 20px 20px;
margin-top: 30px;
margin-bottom: 20px;
font-size: 22px;
line-height: 25px;
color: #555555;
vertical-align: middle;
-webkit-border-radius: 7px;
   -moz-border-radius: 7px;
        border-radius: 7px;
}

input,
textarea,
.uneditable-input {
width: 306px;
}

textarea {
height: auto;
}

textarea,
input[type="text"],
.search-query .uneditable-input {
background-color: #ffffff;
border: 2px solid #c5c5c5;
-webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
   -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
        box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
-webkit-transition: border linear 0.2s, box-shadow linear 0.2s;
   -moz-transition: border linear 0.2s, box-shadow linear 0.2s;
     -o-transition: border linear 0.2s, box-shadow linear 0.2s;
        transition: border linear 0.2s, box-shadow linear 0.2s;
}

.minnesota-california {
	margin-top: -37px;
	margin-left: 145px;
	font-size: 12.5px;
}
</style>

<div class="minnesota-california">
	<p>*We've launched in Minnesota and California.</p>
</div>

<%= search_form_for @search, url: search_caregivers_path, method: :post do |f| %>
  <%= f.condition_fields do |c| %>
    <%= render "condition_fields", f: c %>
  <% end %>
  <p><%= link_to_add_fields "Add Conditions", f, :condition %></p>
  <div class="field">
    Sort:
    <%= f.sort_fields do |s| %>
      <%= s.sort_select %>
    <% end %>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>
<% end %>


<%= paginate @caregivers %>

<div class="caregiver">
<table>
  <tr>
	<th>Photo</th>
    <th>Last Name</th>
	<th>First Name</th>
	<th>Job Title</th>
	<th>City</th>
	<th>Zip Code</th>
  </tr>
<% @caregivers.each do |caregiver| %>
  <div class="return-caregiver-image">
  <tr>
	<td>
    <%= image_tag caregiver.avatar.url(:square) %>
    </td>
	<td>
    <%= caregiver.last_name %>
    </td>
	<td>
    <%= caregiver.first_name %>
    </td>
	<td>
    <%= caregiver.job_title %>
    </td>
	<td>
    <%= caregiver.city %>
    </td>
	<td>
    <%= link_to "Show", caregiver, class: "btn show-btn" %>
    </td>
  </tr>
  </div>
<% end %>
</table>
</div>

<%= paginate @caregivers %>
<% # Parameters to display:
# Avatar
# First name
# Last name
# Job title
# City
# Zip code
%>

app/views/caregivers/new.html.erb
<h1>New Caregiver</h1>

<%= render 'form' %>

<%= link_to 'Back', caregivers_path %>

app/views/caregivers/show.html.erb
<style>
                      

</style>

<div class="sc-verified">
        <%= image_tag('sc-verified.png') %>
    </div>

 <div class="caregiver-avatar">
 <%= image_tag @caregiver.avatar.url(:square) %>
</div>

 <div class="caregiver-basics">
  <div class= "name-profile-headline">
 	<%= @caregiver.first_name %> <%= @caregiver.last_name.first %>.
 </div>

<p>
  <div class="caregiver-job-title">
  <b>Job Title:</b>
  <%= @caregiver.job_title %>
</div>
</p>

<p>
  <b>Years Experience:</b>
  <%= @caregiver.years_experience %>
</p>

<p>
  <b>City:</b>
  <%= @caregiver.city %>
</p>

<p>
  <b>Zip Code:</b>
  <%= @caregiver.zip_code %>
</p>
</div>

<br>
<p>
 <p><b>Bio:</b></p>
  <%= @caregiver.bio %>
</p>
<br>

<b> Requesting an interview is Free! Please include the best way to contact you.</b>

<div>
      <%= mail_to "hello@sugarcare.org", "Request an Interview", :class => "btn request-interview-btn", :subject => "Request Caregiver Interview", :body => "I would like to schedule an interview with #{@caregiver.first_name} #{@caregiver.last_name.first}.









**Please include a brief description of care needed, start date, and your contact information. Thank you!
Original Caregiver URL: #{caregiver_url(@caregiver)}" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>

<title>SugarCare</title>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>

  <style>
* {
  margin: 0;
  padding: 0;
}

html, body {
height: 90%;
}

#main-container {
  min-height: 100%;
  margin: 0 0 0px 0;
}
#footer {
  height: 130px;
  margin: 0px 0 0 0;
  background-color: #f5f5f5;
  padding-top: 25px;
}

.notice {margin-top: 130px;
    }

  #wrap {
  min-height: 100%;
  height: auto !important;
  height: 100%;
  /* Negative indent footer by its height */
  margin: 0 auto 100px;
  /* Pad bottom by footer height */
  padding: 0 0 60px;
}
</style>


<!-- Facebook Registration click through conversion tracking
========================================================================== -->
<script type="text/javascript">
  var fb_param = {};
  fb_param.pixel_id = '6011611621760';
  fb_param.value = '0.00';
  fb_param.currency = 'USD';
  (function(){
  var fpw = document.createElement('script');
  fpw.async = true;
  fpw.src = '//connect.facebook.net/en_US/fp.js';
  var ref = document.getElementsByTagName('script')[0];
  ref.parentNode.insertBefore(fpw, ref);
  })();
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/offsite_event.php?id=6011611621760&amp;value=0&amp;currency=USD" /></noscript>


</head>
<body>
<div id="main-container">
<!-- Main Navigation Links -->
  <div id="front-page-nav" class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">

     <!-- Main SugarCare Logo -->
     <div class="logo">
        <%= link_to image_tag( 'sc_transparent.png'), caregivers_path  %>
     </div>
        <%= link_to "SugarCare.org", caregivers_path, :class => "brand" %>
        <ul class="nav">
        </ul>
        <ul class="nav pull-right">
          <li> 
            <% unless caregiver_signed_in? then %> <%= link_to 'Sign up as a Caregiver', new_caregiver_registration_path %> <% end %></li>
          <% if caregiver_signed_in? %>
          <li>
            <%= link_to "Edit Profile", edit_caregiver_path(current_caregiver) %>
          </li>
          <% end %>
          <li>
            <%= link_to "Log In", new_caregiver_session_path unless caregiver_signed_in? %>
            <%= link_to "Log Out", destroy_caregiver_session_path, :method => :delete if caregiver_signed_in? %>
          </li>
        </ul>

      </div>
    </div>
  </div>


<!-- Application
================================================== -->
<div class="container">
  
<p class="notice"><%= notice %></p>

    <%= yield %>
    
</div>
</body>
</div>
<div id="footer">

<div class="container">
<div class="social">
<!-- Twitter Follow SugarCare
================================================== -->
<a href="https://twitter.com/SugarCare" class="twitter-follow-button" data-show-count="false">Follow @SugarCare</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>


<!-- Twitter, Tweet this!
================================================== -->
 <!--      <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://sugarcare.org" data-text="Make a Caregiver Profile on SugarCare!" data-via="SugarCare">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script> -->


<!-- Facebook HTML 5 Like and Send
================================================== -->
<!-- <div class="fb-like" data-href="http://www.sugarcare.org" data-width="450" data-show-faces="false" data-send="true"></div> -->
</div>

<div>
<p>
Built in Minneapolis and San Francisco
</p>
</div>

<div>
<p>
Copyright 2013.
</p>
</div>

<div class="footer-email">
<p>
<a href="mailto:hello@sugarcare.org?Subject=Hello%20SugarCare!" target="_top">hello@sugarcare.org</a>
</p> 
</div>

<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-37565509-1']);
_gaq.push(['_trackPageview']);

(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
</div>
</div>
</html>